### ISSUE TITLE
Character Sheet and Channel Management

### ISSUE THREAD

**Issue by mazzola** [mazzola/dnd-beyond-dice-chrome-extension#1]
As a player, I would like dice rolls to post in different Discord channels depending on the character that is rolling so that when I am playing multiple campaigns at once, my character's rolls go to the correct channel.

**Comment by mikemfleming** [comment]
I think this would add a lot. How would the average user go about creating a Discord webhook URL? It may be further down the road but would that mean some kind of OAuth process?

**Comment by mazzola** [comment]
Yeah, it's not a great tool for an average user. Right now as it is, a user really has to work together with their Discord admin to set everything up and they need to know [how to generate a webhook url](https://support.discord.com/hc/en-us/articles/228383668). OAuth would definitely help make it easier, but it seems more complex to implement.
